// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBYwp-QnhD76774CEcH97IjbPFSnoHpZE',
    appId: '1:535719807226:web:22010702afefd25855e143',
    messagingSenderId: '535719807226',
    projectId: 'evently-a948b',
    authDomain: 'evently-a948b.firebaseapp.com',
    storageBucket: 'evently-a948b.firebasestorage.app',
    measurementId: 'G-19T0JWVJBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE1SEYfsAy0KJoJLRD8yvnGSRCtquyDq4',
    appId: '1:535719807226:android:e42115247e235c8155e143',
    messagingSenderId: '535719807226',
    projectId: 'evently-a948b',
    storageBucket: 'evently-a948b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4PZhRo8n_gyBaFwlUBg-BsYgNnSBZfqk',
    appId: '1:535719807226:ios:0a82b22cda75dcc455e143',
    messagingSenderId: '535719807226',
    projectId: 'evently-a948b',
    storageBucket: 'evently-a948b.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4PZhRo8n_gyBaFwlUBg-BsYgNnSBZfqk',
    appId: '1:535719807226:ios:0a82b22cda75dcc455e143',
    messagingSenderId: '535719807226',
    projectId: 'evently-a948b',
    storageBucket: 'evently-a948b.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBYwp-QnhD76774CEcH97IjbPFSnoHpZE',
    appId: '1:535719807226:web:401bb8555a194fde55e143',
    messagingSenderId: '535719807226',
    projectId: 'evently-a948b',
    authDomain: 'evently-a948b.firebaseapp.com',
    storageBucket: 'evently-a948b.firebasestorage.app',
    measurementId: 'G-GQ4YMYRHRN',
  );
}
